# Data Source
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/shiro_perm?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai"
    username: root
    password: 123456

---
spring:
  redis:
    host: localhost
    port: 6379  #可不配，因为底层默认值为6379