# Data Source
spring:
  datasource:
    url: "jdbc:mysql://47.96.73.9:3306/shiro_perm?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai"
    username: root
    password: zhouwei!7654321@

---
spring:
  redis:
    host: 47.96.73.9
    port: 6479  #可不配，因为底层默认值为6379